package com.mars.harness.capabilities.migration.engine;

import com.fasterxml.jackson.databind.JsonNode;
import com.mars.harness.capabilities.migration.pack.ReferencePack;
import com.mars.harness.kernel.ports.build.BuildPort;
import com.mars.harness.kernel.ports.capability.CapabilityContext;
import com.mars.harness.kernel.ports.migration.MigrationCapability;

import java.time.LocalDate;
import java.util.Map;

/**
 * The migration report, in the reference renderer's structure (at a glance; what moved; round
 * by round; source changes the upgrade forced; behaviour; what was not caused by the upgrade;
 * what still needs a human; the patch). Outcomes are rendered exactly as recorded. A failed
 * round is never upgraded into a success.
 */
final class MigrationReportRenderer {

    private MigrationReportRenderer() {
    }

    static String render(CapabilityContext context, MigrationCapability.MigrationPlan plan,
                         MigrationCapability.MigrationExecution execution, ReferencePack pack) {
        StringBuilder md = new StringBuilder();
        md.append("# Migration Report — ").append(pack.frontMatter().title()).append("\n\n");
        md.append("_Generated by the unified harness reference-pack engine on ").append(LocalDate.now())
                .append(" from recorded rounds; outcomes are rendered exactly as recorded._\n\n");
        long failed = execution.rounds().stream().filter(r -> r.round() > 0 && !"passed".equals(r.outcome())).count();
        long green = execution.rounds().stream().filter(r -> r.round() > 0 && "passed".equals(r.outcome())).count();
        md.append("## At a glance\n\n| | |\n|---|---|\n");
        md.append("| Result | ").append(result(execution)).append(" |\n");
        md.append("| Platform | Spring Boot ").append(plan.fromVersion()).append(" → ").append(plan.toVersion()).append(" |\n");
        md.append("| Language | Java ").append(plan.fromJava()).append(" → ").append(plan.toJava()).append(" |\n");
        md.append("| Build rounds | ").append(execution.rounds().size()).append(" recorded — 1 pre-migration baseline, ")
                .append(failed).append(" that failed and were read for what to change next, ").append(green).append(" green |\n");
        md.append("| Proposals applied through the Mutation Gateway | ").append(execution.proposalIds().size()).append(" (")
                .append(execution.changeIds().size()).append(" change events) |\n");
        md.append("| Test suite | ").append(execution.tests() == null ? "not compared" : execution.tests().verdict()).append(" |\n");
        md.append("| Runtime behaviour | ").append(execution.behaviour() == null ? "⚠️ Not probed" : execution.behaviour().overall())
                .append(" |\n");
        md.append("| Reference followed | `").append(pack.relativePackPath()).append("` (sha ").append(pack.packSha256(), 0, 12)
                .append(") |\n\n");

        md.append("## Round by round\n\n| Round | Goal | Outcome | Errors | Changed before this round |\n|---|---|---|---|---|\n");
        for (MigrationCapability.RoundRecord r : execution.rounds()) {
            md.append("| ").append(r.round()).append(" | ").append(r.intent()).append(" | ").append(outcome(r.outcome())).append(" | ")
                    .append(r.errorCount()).append(" ").append(r.errorsByCategory().isEmpty() ? "" : r.errorsByCategory()).append(" | ")
                    .append(r.round() == 0 ? r.label() : String.join(", ", r.appliedRules())).append(" |\n");
        }
        for (MigrationCapability.RoundRecord r : execution.rounds()) {
            if (r.errors().isEmpty()) {
                continue;
            }
            md.append("\n<details><summary>Round ").append(r.round()).append(" errors (").append(r.errorCount())
                    .append(")</summary>\n\n");
            for (BuildPort.BuildError e : r.errors()) {
                md.append("- `").append(e.category()).append("` ").append(e.file() == null ? "" : e.file()
                        + (e.line() == null ? "" : ":" + e.line()) + " ").append(e.message().replace("|", "\\|")).append("\n");
            }
            md.append("\n</details>\n");
        }

        md.append("\n## Source changes the upgrade forced\n\n");
        for (MigrationCapability.RoundRecord r : execution.rounds()) {
            if (!r.appliedRules().isEmpty() && r.round() > 0) {
                md.append("- before round ").append(r.round()).append(": ").append(String.join(", ", r.appliedRules()))
                        .append(" — proposals ").append(r.proposalIds()).append("\n");
            }
        }
        md.append("\nEvery change traces to a failing round or to the pack's build-file section; each rule cites its pack section.\n");

        md.append("\n## Does it still behave the same?\n\n");
        MigrationCapability.RuntimeComparison b = execution.behaviour();
        if (b == null) {
            md.append("⚠️ Not probed: the migration did not reach a green round.\n");
        } else {
            md.append("**").append(b.overall()).append("** — verdict `").append(b.verdict()).append("`\n\n");
            if (!b.probes().isEmpty()) {
                md.append("| Probe | Verdict | Before | After | Explanation |\n|---|---|---|---|---|\n");
                b.probes().forEach(p -> md.append("| ").append(p.name()).append(" | ").append(p.verdict()).append(" | ")
                        .append(p.beforeStatus()).append(" | ").append(p.afterStatus()).append(" | ")
                        .append(p.note() == null ? "" : p.note()).append(" |\n"));
            }
            b.explanations().forEach(e -> md.append("\n- ").append(e));
            md.append("\n");
        }
        md.append("\nThe test suite, before and after: ").append(execution.tests() == null ? "not compared"
                : execution.tests().verdict()).append("\n");

        md.append("\n## Changes that were *not* caused by the upgrade\n\n_None — every applied change is a pack rule.");
        md.append(" Not required by this jump (pack §10): ");
        JsonNode notRequired = pack.rules().path("not_required");
        notRequired.forEach(n -> md.append(n.asText()).append("; "));
        md.append("_\n\n## What still needs a human\n\n");
        if (execution.needsHumanReason() != null) {
            md.append("- ").append(execution.needsHumanReason()).append("\n");
        }
        execution.unmatchedErrors().forEach(u -> md.append("- unmatched: ").append(u).append("\n"));
        if (execution.needsHumanReason() == null && execution.unmatchedErrors().isEmpty()) {
            md.append("- Review the behaviour differences above before calling the migration behaviour-neutral.\n");
        }
        md.append("\n## The patch\n\nThe cumulative patch of every gateway-applied change is `reports/cumulative.patch`. "
                + "Applying it to the project is a separate, explicit, decision-bound step (`harness apply`), refused unless the "
                + "last round is green.\n");
        return md.toString();
    }

    private static String result(MigrationCapability.MigrationExecution e) {
        MigrationCapability.RoundRecord last = e.rounds().isEmpty() ? null : e.rounds().get(e.rounds().size() - 1);
        return switch (e.status()) {
            case GREEN -> "🟢 Green on JDK " + (last == null ? "?" : last.jdk()) + " after " + (e.rounds().size() - 1) + " round(s)";
            case NEEDS_HUMAN -> "🟠 Needs a human after " + (e.rounds().size() - 1) + " round(s)";
            case ROUND_LIMIT -> "🔴 Round limit reached without a green round";
            default -> "🔴 " + e.status();
        };
    }

    private static String outcome(String id) {
        Map<String, String> labels = Map.of("passed", "🟢 Passed", "compile-failed", "🔴 Compile failed", "dependency-failed",
                "🔴 Dependencies unresolved", "tests-failed", "🟠 Tests failed", "timed-out", "🟠 Timed out");
        return labels.getOrDefault(id, "⚪ " + id);
    }
}
